// DSH owns the palette, typography, controls and theme switching. These rules
// only arrange the Project surfaces and mirror the official sidebar geometry.
export const styles = `
.project-panel{box-sizing:border-box;font-family:var(--dsw-font-family);font-size:14px;line-height:22px;color:var(--dsw-alias-label-primary)}
.project-panel button:focus-visible{outline:2px solid var(--dsw-alias-label-primary);outline-offset:-2px}
.project-brand-mark{display:inline-flex;align-items:center;justify-content:center;flex:none}
.project-brand-title{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.project-panel-icon{display:inline-flex;align-items:center;justify-content:center;flex:none}.project-panel-count{flex:none;margin-left:auto;font-size:12px;line-height:18px;font-variant-numeric:tabular-nums;color:var(--dsw-alias-label-tertiary);pointer-events:none}
.project-session-browser{--dsh-session-list-edge-inset:var(--dsh-sidebar-inline-padding);--dsh-session-list-scrollbar-width:8px;--dsh-session-list-scrollbar-offset:2px;box-sizing:border-box;flex:1;min-height:0;display:flex;flex-direction:column;padding-right:var(--dsh-session-list-edge-inset)}.project-session-browser.rail{padding-right:0}
.project-session-header{flex:none;display:flex;align-items:center;justify-content:flex-end;gap:4px;height:36px;padding-left:4px;margin:2px -4px 4px 0;box-sizing:border-box;border-radius:12px;overflow:hidden;color:var(--dsw-alias-label-tertiary)}
.project-section-label{flex:none;max-width:45%;min-width:0;overflow:hidden;white-space:nowrap;font-size:14px;line-height:20px;opacity:1;visibility:visible;transition:max-width 180ms var(--ds-ease-in-out),margin-right 180ms var(--ds-ease-in-out),opacity 120ms var(--ds-ease-in-out),transform 180ms var(--ds-ease-in-out),visibility 0s linear}.project-section-label.hidden{max-width:0;margin-right:-4px;opacity:0;transform:translateX(-4px);visibility:hidden;transition-delay:0s,0s,0s,0s,180ms}
.project-session-search-slot{flex:1;max-width:28px;min-width:0;display:flex;align-items:center;margin-left:auto;box-sizing:border-box;transition:max-width 180ms var(--ds-ease-in-out)}.project-session-search-slot.expanded{max-width:100%}
.project-session-header-actions{flex:none;display:flex;align-items:center;max-width:32px;opacity:1;overflow:hidden;visibility:visible;transition:max-width 180ms var(--ds-ease-in-out),opacity 120ms var(--ds-ease-in-out),transform 180ms var(--ds-ease-in-out),visibility 0s linear}.project-session-header-actions.hidden{max-width:0;opacity:0;transform:translateX(4px);visibility:hidden;pointer-events:none;transition-delay:0s,0s,0s,180ms}
.project-session-icon-button,.project-session-search-button,.project-session-search-clear,.project-session-row-action{flex:none;display:inline-flex;align-items:center;justify-content:center;border:0;padding:0;background:transparent;cursor:pointer;color:inherit}.project-session-icon-button{width:28px;height:28px;border-radius:50%;corner-shape:round;color:var(--dsw-alias-label-secondary)}.project-session-icon-button:hover,.project-session-search-button:hover,.project-session-search-clear:hover{background:var(--dsw-alias-interactive-bg-hover)}
.project-session-search{display:flex;align-items:center;width:100%;height:28px;box-sizing:border-box;border:.5px solid transparent;border-radius:50%;corner-shape:round;overflow:hidden;color:var(--dsw-alias-label-secondary);cursor:text;transition:width 180ms var(--ds-ease-in-out),padding 180ms var(--ds-ease-in-out),border-color 180ms var(--ds-ease-in-out)}.project-session-search.expanded{width:calc(100% + 4px);height:30px;margin-inline:-2px;padding-right:4px;border-color:var(--dsw-alias-border-l4);border-radius:10px;color:var(--dsw-alias-label-caption)}.project-session-search-button{width:28px;height:28px;border-radius:50%;corner-shape:round}.project-session-search.expanded .project-session-search-button{height:30px}.project-session-search.expanded .project-session-search-button:hover{background:transparent}
.project-session-search-input{flex:1;width:0;min-width:0;border:0;outline:0;background:transparent;opacity:0;pointer-events:none;font-size:13px;line-height:18px;color:var(--dsw-alias-label-primary);transition:opacity 120ms var(--ds-ease-in-out)}.project-session-search.expanded .project-session-search-input{margin-left:-2px;opacity:1;pointer-events:auto}.project-session-search-input::placeholder{color:var(--dsw-alias-label-tertiary)}.project-session-search-clear{width:24px;height:24px;border-radius:50%;corner-shape:round;color:var(--dsw-alias-label-secondary)}
.project-session-rail-search{flex:none;margin-bottom:12px}.project-session-rail-search .project-session-search-button{width:36px;height:36px;color:var(--dsw-alias-label-primary)}
.project-session-list-area{flex:1;min-height:0;display:flex;flex-direction:column;margin-left:-4px;margin-right:calc(-1 * var(--dsh-session-list-edge-inset));padding-left:4px;overflow:visible}.rail .project-session-list-area{margin-left:0;margin-right:0;padding-left:0}.project-session-tree-body{flex:1;min-height:0;display:flex;flex-direction:column;position:relative;animation:project-session-wide-in 200ms var(--ds-ease-in-out)}.project-session-fade{position:absolute;left:0;right:var(--dsh-session-list-edge-inset);bottom:0;height:24px;background:linear-gradient(to bottom,transparent,var(--dsw-specific-sidebar-fill));pointer-events:none}@keyframes project-session-wide-in{from{opacity:0}}
.project-session-list{flex:1;min-height:0;overflow-y:auto;margin-left:-4px;margin-right:var(--dsh-session-list-scrollbar-offset);padding-left:4px;padding-right:calc(var(--dsh-session-list-edge-inset) - var(--dsh-session-list-scrollbar-width) - var(--dsh-session-list-scrollbar-offset));padding-bottom:16px;scrollbar-gutter:stable}.project-session-list>span{display:block}.project-session-list.flat>*+*,.project-session-list.search>[role=treeitem]+[role=treeitem]{margin-top:2px}
.project-session-row{box-sizing:border-box;display:flex;align-items:center;gap:0;height:32px;padding:0 8px;border-radius:8px;cursor:pointer;user-select:none;color:var(--dsw-alias-label-primary);animation:project-session-row-in 150ms var(--ds-ease-in-out)}.project-session-row:hover,.project-session-row.selected,.project-session-row.menu-open{background:var(--dsw-alias-interactive-bg-hover)}@keyframes project-session-row-in{from{opacity:0}}
.project-session-status{flex:none;width:16px;height:20px;display:inline-flex;align-items:center;justify-content:center;color:var(--dsw-alias-label-tertiary)}.project-session-title{flex:1;min-width:0;margin:0 6px 0 4px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:14px;line-height:20px}.project-session-title.no-status{margin-left:0}.project-session-time{flex:none;font-size:12px;line-height:20px;color:var(--dsw-alias-label-tertiary)}
.project-session-schedule{display:inline-flex;flex:none;width:16px;height:20px;align-items:center;justify-content:center;margin-right:6px;color:var(--dsw-alias-label-tertiary)}.project-session-schedule.search{margin-right:0;margin-left:4px}.project-session-actions{flex:none;display:none;align-items:center;gap:12px}.project-session-row:hover .project-session-actions,.project-session-row.menu-open .project-session-actions{display:inline-flex}.project-session-row:hover .project-session-time,.project-session-row.menu-open .project-session-time{display:none}.project-session-row-action{width:16px;height:16px;border-radius:4px;color:var(--dsw-alias-label-tertiary)}.project-session-row-action:hover{color:var(--dsw-alias-label-primary)}
.project-session-row.drop-before,.project-session-row.drop-after{position:relative}.project-session-row.drop-before::before,.project-session-row.drop-after::after{content:'';position:absolute;z-index:1;left:0;right:4px;height:12px;background:linear-gradient(55deg,transparent calc(50% - 1px),var(--dsw-alias-state-business-primary) calc(50% - 1px) calc(50% + 1px),transparent calc(50% + 1px)) 0 0/5px 7px no-repeat,linear-gradient(125deg,transparent calc(50% - 1px),var(--dsw-alias-state-business-primary) calc(50% - 1px) calc(50% + 1px),transparent calc(50% + 1px)) 0 5px/5px 7px no-repeat,linear-gradient(var(--dsw-alias-state-business-primary) 0 0) 4px 5px/calc(100% - 4px) 2px no-repeat;pointer-events:none}.project-session-row.drop-before::before{top:-7px}.project-session-row.drop-after::after{bottom:-7px}
.project-session-hover{display:flex;flex-direction:column;gap:8px}.project-session-hover strong{font-size:14px;line-height:20px;color:#fff;overflow-wrap:break-word}.project-session-hover>span{font-size:12px;line-height:16px;color:#cfd3d6}.project-session-hover .project-session-hover-status{display:flex;align-items:center;gap:8px;line-height:20px;color:#adb2b8}.project-visually-hidden{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}
.project-session-search-result{display:flex;flex-direction:column;align-items:stretch;width:100%;min-height:48px;box-sizing:border-box;border:0;border-radius:8px;padding:4px 8px;background:transparent;cursor:pointer;text-align:left;color:var(--dsw-alias-label-primary)}.project-session-search-result:hover,.project-session-search-result.selected{background:var(--dsw-alias-interactive-bg-hover)}.project-session-search-heading{display:flex;align-items:center;min-width:0}.project-session-search-title{flex:0 1 auto;min-width:0;margin-left:4px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:14px;line-height:20px}.project-session-search-meta{display:flex;align-items:center;min-width:0;margin-left:20px}.project-session-search-snippet{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px;line-height:17px;color:var(--dsw-alias-label-secondary)}
.project-session-search-status,.project-session-search-warning{padding:10px 12px;font-size:12px;line-height:18px;color:var(--dsw-alias-label-tertiary)}.project-session-search-warning{color:var(--dsw-alias-label-secondary)}.project-session-empty{padding:16px 12px;color:var(--dsw-alias-label-tertiary);font-size:13px}.project-session-rename-input{box-sizing:border-box;width:100%;min-width:0}.project-session-rename-input input{width:100%;min-width:0}.project-session-rename-error{margin-top:8px;font-size:12px;line-height:18px;color:var(--dsw-alias-state-error-primary)}
@media (prefers-reduced-motion:reduce){.project-session-tree-body,.project-session-row{animation:none}.project-session-search,.project-section-label,.project-session-search-slot,.project-session-search-input,.project-session-header-actions{transition:none}}
/* Desktop AdvancedFrame and the official RightbarSeat animate independently;
   panel navigation restores both within one transition-free frame. */
html[data-project-panel-switching] .dshDesktopFrame,
html[data-project-panel-switching] .dshDesktopResizeHandle,
html[data-project-panel-switching] [data-sidebar-right-panel]{transition:none!important}
/* Match WorkspaceBrowser.list: place the stable themed scrollbar inside the
   existing right inset so all seven pages retain the same content width. */
.project-panel{height:100%;overflow:auto;scrollbar-gutter:stable;padding:28px clamp(20px,4vw,48px);padding-right:calc(clamp(20px,4vw,48px) - var(--dsh-scrollbar-width,8px));background:var(--dsw-alias-bg-base)}
.project-panel>header{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:24px}.project-panel>header>div{min-width:0}.project-panel>header>button{flex:none}.project-panel h1{font-size:24px;font-weight:600;line-height:32px;margin:4px 0 8px;overflow-wrap:anywhere}.project-panel h2{font-size:16px;font-weight:600;line-height:24px;margin:0 0 12px}.project-panel h3{display:flex;align-items:center;gap:8px;font-size:14px;font-weight:500;line-height:22px;margin:16px 0 8px}.project-panel h3 svg{flex:none}.project-panel p{color:var(--dsw-alias-label-secondary);line-height:22px;overflow-wrap:anywhere}
.project-panel .project-eyebrow{font-size:12px;line-height:18px;margin:0;color:var(--dsw-alias-label-tertiary)}.project-panel section{margin-bottom:24px}.project-summary{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:16px}
.project-card{border:0.5px solid var(--dsw-alias-border-l3);border-radius:12px;padding:20px;min-width:0;background:var(--dsw-alias-bg-layer-1)}.project-card-actions{margin-top:16px}.project-panel code{font-family:var(--ds-font-family-code);font-size:12px;line-height:20px;overflow-wrap:anywhere;color:var(--dsw-alias-label-tertiary)}
.project-capability-card{display:flex;flex-direction:column;align-items:flex-start;gap:12px}.project-capability-card p{margin:0;max-width:720px}
.project-card-top{display:flex;justify-content:space-between;align-items:center;gap:8px}.project-error{color:var(--dsw-alias-state-error-primary)!important;font-size:12px;overflow-wrap:anywhere}
.project-resource-branch{display:flex;align-items:center;gap:4px;min-width:0;margin-left:auto;font-size:12px;color:var(--dsw-alias-label-secondary)}.project-resource-branch svg{flex:none}
/* Keep the Agent Preset card chrome; clamp summaries and read full values in the shared Modal. */
.project-resource-card{box-sizing:border-box;height:168px}.project-resource-card>.project-mcp-card-body{min-height:0;overflow:clip}.project-resource-card>.project-mcp-card-body>*{flex-shrink:0}
.project-resource-card .project-mcp-name,.project-resource-branch>span,.project-resource-location>span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.project-resource-card .project-summary{flex-wrap:nowrap;align-items:center}.project-resource-card .project-summary>span:not(.project-resource-branch):not(.project-resource-sync-label){flex:none}
.project-resource-metadata{display:flex;align-items:center;gap:8px;min-width:0;font-size:13px;line-height:20px;color:var(--dsw-alias-label-secondary)}.project-resource-metadata>svg{flex:none;color:var(--dsw-alias-label-tertiary)}
.project-resource-location{display:flex;min-width:0}.project-resource-location-parent{color:var(--dsw-alias-label-tertiary);flex:0 1 auto}.project-resource-location-name{flex:0 0 auto;max-width:100%}.project-resource-location-parent+.project-resource-location-name{max-width:80%}
.project-resource-card>.project-mcp-card-footer{flex:none}.project-resource-details-action{margin-right:auto}
.project-resource-card .project-summary>.project-resource-sync-label{flex:0 1 auto;min-width:0;overflow:hidden}.project-resource-sync-label>span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.project-resource-details .project-setting-row-stacked>.project-setting-control{justify-content:flex-start;overflow-wrap:anywhere}.project-resource-details code{white-space:pre-wrap;overflow-wrap:anywhere;min-width:0;font-size:12px;line-height:20px}.project-resource-details .project-setting-row:last-child{border-bottom:0}
.project-resource-directory{display:flex;align-items:center;flex-wrap:wrap;gap:10px;min-width:0}.project-resource-directory code{flex:1;min-width:0;overflow-wrap:anywhere}.project-resource-directory button{flex:none}
.project-resource-operations{margin-top:28px}.project-resource-operation{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;padding:12px 0;border-bottom:.5px solid var(--dsw-alias-border-l3)}.project-resource-operation>div:first-child{flex:1;min-width:0}.project-resource-operation p{margin:4px 0}.project-resource-operation strong{overflow-wrap:anywhere}.project-resource-operation-actions{display:flex;flex:none;flex-wrap:wrap;align-items:center;gap:6px}
@media(max-width:600px){.project-resource-operation{flex-direction:column}.project-resource-operation-actions{align-self:flex-end}}
.project-memory{display:grid;gap:16px}.project-memory-card{padding:0;border-radius:8px;overflow:hidden}.project-memory-header{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 20px;border-bottom:.5px solid var(--dsw-alias-border-l3)}.project-memory-header h2{min-width:0;margin:0;overflow-wrap:anywhere}.project-memory-action-anchor{display:inline-flex}.project-memory-markdown{min-width:0;padding:18px 20px 22px;overflow-wrap:anywhere}.project-memory-markdown>:first-child{margin-top:0}.project-memory-markdown>:last-child{margin-bottom:0}.project-memory-markdown h1{font-size:20px;line-height:28px}.project-memory-markdown h2{font-size:17px;line-height:25px}.project-memory-markdown h3{font-size:15px;line-height:23px}.project-memory-markdown img{max-width:100%;height:auto}.project-memory-editor{display:grid;gap:12px;padding:16px 20px 18px}.project-memory-editor textarea{box-sizing:border-box;width:100%;min-height:300px;resize:vertical;padding:12px 14px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;outline:0;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);font-family:var(--ds-font-family-code);font-size:13px;line-height:20px;tab-size:2}.project-memory-editor textarea:hover{border-color:var(--dsw-alias-label-dimmed)}.project-memory-editor textarea:focus{border-color:var(--dsw-alias-brand-primary);box-shadow:0 0 0 1px var(--dsw-alias-brand-primary)}.project-memory-editor textarea:disabled{opacity:.6}.project-memory-editor-footer{display:flex;align-items:center;justify-content:space-between;gap:12px;min-width:0}.project-memory-editor-footer>span{font-size:12px;color:var(--dsw-alias-label-tertiary)}.project-memory-editor-actions{display:flex;justify-content:flex-end;gap:8px}.project-memory-editor>.project-error{margin:0}

.project-catalog-context{font-size:12px;overflow-wrap:anywhere}
/* ui-agent-preset/AgentPresetSection.module.css: private roster/card chrome with a public Button/Modal reader. */
.project-panel .project-tool-group{margin-bottom:32px}.project-panel .project-tool-group>h2{display:flex;align-items:center;gap:8px;margin:0 0 10px;font-size:12px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:var(--dsw-alias-label-tertiary)}
.project-tool-grid,.project-mcp-grid,.project-skill-grid{list-style:none;margin:0;padding:0;display:grid;grid-template-columns:repeat(auto-fill,minmax(min(100%,268px),1fr));grid-auto-rows:1fr;gap:12px}
.project-tool-card,.project-mcp-card,.project-skill-card{min-width:0;display:flex;flex-direction:column;border:.5px solid var(--dsw-alias-border-l4);border-radius:20px;background:transparent;transition:border-color .16s,background .16s}
.project-tool-card:hover,.project-mcp-card:hover,.project-skill-card:hover{background:var(--dsw-alias-interactive-bg-hover)}
button.project-tool-main{box-sizing:border-box;flex:1;width:100%;height:auto;min-width:0;display:flex;flex-direction:column;align-items:stretch;justify-content:flex-start;gap:8px;padding:14px 16px 12px;border:0;border-radius:20px;background:none;font:inherit;text-align:left;white-space:normal;color:var(--dsw-alias-label-primary)}
button.project-tool-main:hover:not(:disabled),button.project-tool-main:active:not(:disabled){background:none}.project-panel button.project-tool-main:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:-2px}
.project-tool-name,.project-mcp-name,.project-skill-name{min-width:0;font-size:15px;font-weight:600;line-height:1.4;overflow-wrap:anywhere}
.project-tool-description{font-size:13px;line-height:1.55;color:var(--dsw-alias-label-secondary);min-height:42px;display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:4;overflow:hidden;overflow-wrap:anywhere;white-space:pre-wrap}
.project-tool-full-description{margin:0;white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px;line-height:1.55;color:var(--dsw-alias-label-secondary)}
.project-capability-toolbar{display:flex;align-items:center;flex-wrap:wrap;gap:10px;margin-bottom:20px}.project-capability-toolbar>span,.project-meta{font-size:12px;color:var(--dsw-alias-label-tertiary)}.project-toolbar-toggle{display:flex;align-items:center;gap:12px}
.project-capability-layout{display:grid;grid-template-columns:minmax(180px,1fr) minmax(300px,2fr);gap:18px;align-items:start}.project-capability-list{display:grid;gap:8px}.project-capability-list .project-task-choice{display:grid;justify-content:stretch;gap:10px;text-align:left;width:100%;height:auto;min-width:0;padding:16px;overflow-wrap:anywhere}.project-task-choice[aria-pressed=true]{background:var(--dsw-alias-interactive-bg-hover)}.project-task-choice>span{display:flex;flex-wrap:wrap;gap:6px}.project-task-choice small{font-size:12px;color:var(--dsw-alias-label-tertiary)}
.project-task-detail .project-card-top{align-items:flex-start}.project-task-detail h2{margin:0;overflow-wrap:anywhere}.project-card-actions{display:flex;gap:8px;flex-wrap:wrap}.project-prose{white-space:pre-wrap}.project-artifacts{padding-left:18px;overflow-wrap:anywhere}.project-artifacts li+li{margin-top:8px}.project-artifacts button{height:auto;min-height:28px;white-space:normal;text-align:left}.project-artifacts a{color:var(--dsw-alias-label-primary)}.project-empty-state{padding:32px}
/* Task content uses the page's single stable scroll area; history never adds a nested scroller. */
.project-tasks{min-width:0;container:project-tasks / inline-size}.project-capability-list .project-task-choice{white-space:normal}
.project-task-toolbar>span:first-child{flex:1;min-width:min(100%,220px);max-width:360px}.project-task-toolbar input{min-width:0;width:100%}
.project-task-roster,.project-task-detail,.project-task-detail .project-card-top>h2{min-width:0}.project-task-detail{overflow-wrap:anywhere}.project-task-detail .project-card-top{flex-wrap:wrap}.project-task-detail .project-card-top>h2{flex:1 1 180px}
.project-task-choice .project-task-excerpt{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:3;overflow:hidden;white-space:pre-wrap;color:var(--dsw-alias-label-secondary);font-size:13px;line-height:20px;font-weight:400}
.project-task-pagination{display:grid;gap:8px;margin-top:16px}.project-task-tags{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.project-task-detail>.project-task-tags{margin-top:12px}
.project-task-section{min-width:0;margin-top:22px;padding-top:16px;border-top:.5px solid var(--dsw-alias-border-l3)}.project-task-section h3{margin:0 0 10px;font-size:14px;line-height:22px}.project-task-section h4{margin:12px 0 6px;font-size:13px;line-height:20px}.project-task-section p{margin:6px 0}.project-task-text-list{margin:6px 0;padding-left:20px}.project-task-text-list li+li{margin-top:6px}
.project-task-history,.project-task-criteria,.project-task-participants{list-style:none;padding:0;margin:0}.project-task-history>li,.project-task-criteria>li{padding:12px 0;min-width:0}.project-task-history>li+li,.project-task-criteria>li+li{border-top:.5px solid var(--dsw-alias-border-l3)}.project-task-history>li:first-child,.project-task-criteria>li:first-child{padding-top:0}.project-task-verification{margin-top:10px;color:var(--dsw-alias-label-secondary);font-size:13px;line-height:20px}.project-task-verification p{margin:4px 0}.project-task-participants{display:grid;gap:10px}.project-task-participants>li{min-width:0;display:flex;flex-wrap:wrap;gap:6px;align-items:center}.project-task-participants button{max-width:100%;height:auto;white-space:normal;overflow-wrap:anywhere;text-align:left}.project-task-history button{height:auto;white-space:normal;overflow-wrap:anywhere;text-align:left}
.project-task-diagnostics{margin:0 0 20px;padding:12px 0;overflow-wrap:anywhere;color:var(--dsw-alias-label-secondary)}.project-task-diagnostics h3{font-size:13px;margin:0 0 8px}.project-task-diagnostics ul{margin:0;padding-left:18px}.project-task-diagnostics li+li{margin-top:8px}.project-task-diagnostics code{display:block;font-size:12px}.project-task-diagnostics span{font-size:13px}.project-task-detail>.project-task-diagnostics{margin:12px 0 0}.project-task-prepared{margin:12px 0}.project-task-prepared p{margin:8px 0}

/* Skills use the same compact Agent Preset card grid as MCP while retaining their own metadata. */
.project-skill-grid{grid-auto-rows:auto}.project-skill-card-body{flex:1;min-width:0;display:flex;flex-direction:column;gap:8px;padding:12px 16px}.project-skill-card p{margin:0}
.project-skill-description,.project-skill-usage{font-size:13px;line-height:1.55;color:var(--dsw-alias-label-secondary);overflow-wrap:anywhere;white-space:pre-wrap}
.project-skill-usage{color:var(--dsw-alias-label-tertiary)}.project-skill-meta{font-size:12px;line-height:20px;color:var(--dsw-alias-label-tertiary);overflow-wrap:anywhere}
.project-skill-heading{display:flex;flex:1;min-width:0;flex-wrap:wrap;align-items:center;gap:6px}.project-skill-heading>:last-child,.project-skill-card .project-card-top>:last-child{flex:none}.project-skill-tags{display:flex;flex-wrap:wrap;align-items:center;gap:6px;margin-top:auto}
/* AgentPresetSection cardMain/cardFoot/iconButton: compact service details and a separate action strip. */
.project-mcp-grid{grid-auto-rows:auto} /* Stretch within each row; one verbose service must not enlarge every row. */
.project-mcp-card-body{flex:1;min-width:0;display:flex;flex-direction:column;gap:6px;padding:12px 16px 10px}.project-mcp-card .project-summary,.project-mcp-card p{margin:0}.project-mcp-card .project-summary{gap:6px}
.project-mcp-metadata{display:flex;flex-wrap:wrap;align-items:baseline;gap:0 10px;min-width:0}
.project-panel .project-mcp-endpoint{min-width:0;max-width:100%;display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2;overflow:hidden;font-size:11px}.project-panel .project-mcp-local{font-size:12px;line-height:20px;color:var(--dsw-alias-label-tertiary)}
/* Keep two lines visible, with keyboard scrolling for additional names; discovery never expands the grid. */
.project-mcp-tools{box-sizing:border-box;flex:none;min-width:0;height:40px;margin-top:auto;overflow-x:hidden;overflow-y:auto;overscroll-behavior:contain;scrollbar-gutter:stable;border-radius:4px}
.project-mcp-tools:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:2px}
.project-mcp-tools ul{display:flex;flex-direction:column;list-style:none;margin:0;padding:0;overflow-wrap:anywhere}.project-mcp-tools li{min-width:0;line-height:20px}.project-mcp-tools code{display:block}
.project-mcp-card-footer{display:flex;justify-content:flex-end;gap:2px;padding:6px 10px;border-top:.5px solid var(--dsw-alias-border-l2)}.project-mcp-action-anchor{display:inline-flex}
.project-mcp-error-anchor{margin-right:auto}
.project-mcp-error-icon{color:var(--dsw-alias-state-error-primary)}
button.project-mcp-action{width:28px;height:28px;padding:6px;border:0;border-radius:7px;background:none;color:var(--dsw-alias-label-tertiary)}button.project-mcp-action:disabled{opacity:.4}
button.project-mcp-action:hover:not(:disabled){background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary)}button.project-mcp-action-danger:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover-danger);color:var(--dsw-alias-state-error-primary)}.project-panel button.project-mcp-action:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:-1px}
/* LanguageRow.module.css owns this selector fill and spacing; Menu owns its popup. */
.project-select,.project-select>span{display:inline-flex;min-width:0;max-width:100%}
.project-select .project-select-trigger{min-width:0;max-width:100%;gap:12px;background:var(--dsw-alias-bg-module-platform);font:inherit;font-size:14px;line-height:22px}
.project-select-trigger>span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.project-select-trigger>svg{flex:none}
.project-select .project-select-trigger:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}
/* ModelsSection.module.css: addButton and iconButton, composed with shared Buttons. */
button.project-add-button{box-sizing:border-box;width:100%;min-width:0;gap:6px;height:44px;border:1px dashed var(--dsw-alias-border-l3);border-radius:16px}
.project-secret-row .project-remove-value{box-sizing:border-box;width:28px;height:28px;padding:0;border-radius:6px;color:var(--dsw-alias-label-tertiary)}
.project-secret-row .project-remove-value:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover-danger);color:var(--dsw-alias-state-error-primary)}
.project-select-trigger:focus-visible,.project-add-button:focus-visible,.project-remove-value:focus-visible{outline:none;box-shadow:0 0 0 2px var(--dsw-alias-border-l3)}
/* No public Textarea exists in the pinned primitives; use the official input tokens. */
.project-textarea{box-sizing:border-box;width:100%;min-width:0;max-width:100%;min-height:96px;padding:8px 10px;border:.5px solid var(--dsw-alias-border-l4);border-radius:8px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font:inherit;font-family:var(--ds-font-family-code);resize:vertical}
.project-textarea:focus{outline:none;border-color:var(--dsw-alias-brand-primary)}.project-textarea:disabled{opacity:.6;cursor:default}
.project-disclosure{min-width:0}.project-disclosure-content{display:grid;gap:16px;padding-top:12px}.project-disclosure-content[hidden]{display:none}
/* ui-settings-plugins/PluginCard.module.css: private Subagent card chrome, composed with shared Button. */
.project-settings-card{min-width:0;border:.5px solid var(--dsw-alias-border-l4);border-radius:16px;background:var(--dsw-alias-bg-layer-3);transition:border-color .16s,background .16s}
.project-settings-card:hover{border-color:var(--dsw-alias-label-dimmed)}.project-settings-card[data-open=true]{background:var(--dsw-alias-bg-layer-2);border-color:var(--dsw-alias-label-dimmed)}
button.project-settings-card-header{box-sizing:border-box;width:100%;height:auto;min-width:0;gap:12px;padding:14px 16px;border-radius:12px;font:inherit;text-align:left;background:none}
button.project-settings-card-header:hover:not(:disabled),button.project-settings-card-header:active:not(:disabled){background:none}
button.project-settings-card-header:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:-2px}
.project-settings-card-copy{display:flex;flex:1;flex-direction:column;gap:4px;min-width:0;overflow-wrap:anywhere}
.project-settings-card-title{font-size:15px;font-weight:600;line-height:1.4;color:var(--dsw-alias-label-primary)}
.project-settings-card-description{font-size:13px;line-height:1.5;color:var(--dsw-alias-label-tertiary)}
.project-settings-card-chevron{flex:none;color:var(--dsw-alias-label-tertiary);transition:transform .16s}.project-settings-card[data-open=true] .project-settings-card-chevron{transform:rotate(180deg)}
.project-settings-card-body{min-width:0;margin:0 16px;padding-bottom:8px;border-top:.5px solid var(--dsw-alias-border-l2)}.project-settings-card-body[hidden]{display:none}
/* DesktopSettingsSection.ToggleRow is private: adapt its switch, using ordinary setting rows. */
button.project-desktop-switch{width:40px;height:22px;border-radius:999px;background:var(--dsw-alias-border-l2);transition:background-color var(--ds-transition-duration-fast) var(--ds-ease-in-out)}
button.project-desktop-switch[aria-checked=true]{background:var(--dsw-alias-brand-primary)}
button.project-desktop-switch>span{width:18px;height:18px;box-shadow:0 1px 2px rgba(0,0,0,.24);transform:translateX(0);transition:transform var(--ds-transition-duration-fast) var(--ds-ease-in-out)}
button.project-desktop-switch[role=switch][aria-checked=true]>span{transform:translateX(18px)}
button.project-desktop-switch:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:2px}
/* LanguageRow/official Setting-Cell: copy left, control right, 16px insets and hairline rows. */
.project-setting-row{display:flex;align-items:center;gap:24px;min-width:0;padding:16px 0;border-bottom:.5px solid var(--dsw-alias-border-l2)}
.project-setting-copy{display:flex;flex:1;flex-direction:column;gap:4px;min-width:0;overflow-wrap:anywhere}
.project-setting-title{font-size:14px;font-weight:400;line-height:22px;color:var(--dsw-alias-label-primary)}
.project-setting-description{margin:0;font-size:12px;line-height:20px;color:var(--dsw-alias-label-tertiary)}
.project-setting-control{display:flex;justify-content:flex-end;flex:0 1 auto;min-width:0;max-width:52%}
.project-setting-row-input>.project-setting-control{width:52%}
.project-setting-row-stacked{flex-direction:column;align-items:stretch;gap:12px}
.project-setting-row-stacked>.project-setting-control{width:100%;max-width:100%}
.project-mcp-reconnect{padding-top:16px}.project-mcp-reconnect .project-setting-row:last-child{border-bottom:0}
/* Match SettingsRoot.options: the Modal body owns scrolling and 24px content
   insets; reserve its themed scrollbar inside the existing right inset. */
[role=dialog].project-settings-dialog{box-sizing:border-box;width:min(660px,100%);max-height:calc(100dvh - 48px)}
.project-settings-dialog h2{overflow-wrap:anywhere}
.project-settings-dialog .project-settings-dialog-content{min-width:0;min-height:0}
.project-settings-dialog-content>div:first-child,.project-settings-dialog-content>p{flex:none}
.project-settings-dialog-content>div:last-child{min-height:0;margin-top:12px;overflow-x:hidden;overflow-y:auto;overscroll-behavior:contain;scrollbar-gutter:stable;padding-right:calc(24px - var(--dsh-scrollbar-width,8px))}
.project-settings-dialog>div:last-child{flex:none;flex-wrap:wrap}
.project-capability-form{box-sizing:border-box;min-width:0;min-height:0;color:var(--dsw-alias-label-primary);font-family:var(--dsw-font-family);font-size:14px;line-height:22px;container:project-mcp-form / inline-size}
.project-capability-form fieldset{min-width:0;border:0;padding:0;margin:0}
/* Input wraps a native input in a flex span; both must shrink inside grid cells. */
.project-setting-row-input>.project-setting-control>span,.project-secret-row>span{box-sizing:border-box;width:100%;min-width:0;max-width:100%}
.project-capability-form input{width:100%;min-width:0}
.project-secret-list{display:grid;gap:12px;width:100%;min-width:0}
.project-secret-row{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr) auto;gap:12px;align-items:center}
.project-form-success{color:var(--dsw-alias-label-primary)}
@container project-mcp-form (max-width:520px){.project-setting-row{flex-direction:column;align-items:stretch;gap:12px}.project-setting-control,.project-setting-row-input>.project-setting-control{justify-content:flex-start;max-width:100%;width:100%}}
@container project-mcp-form (max-width:480px){.project-secret-row{grid-template-columns:minmax(0,1fr) auto}.project-secret-row>span{grid-column:1}.project-secret-row>button{grid-column:2;grid-row:1 / 3}}
@media(prefers-reduced-motion:reduce){button.project-desktop-switch,button.project-desktop-switch>span,.project-settings-card,.project-settings-card-chevron,.project-tool-card,.project-mcp-card,.project-skill-card{transition:none}}
@media(max-width:760px){.project-capability-layout{grid-template-columns:minmax(0,1fr)}.project-capability-list{grid-template-columns:repeat(auto-fit,minmax(160px,1fr))}.project-task-detail .project-card-top{flex-wrap:wrap}.project-memory-editor-footer{align-items:flex-start;flex-direction:column}.project-memory-editor-actions{width:100%;flex-wrap:wrap}}

/* Task list/detail scroll independently; the official frame owns file previews. */
.project-panel-actions{display:flex;align-items:center;gap:8px;flex:none}
.project-panel.project-tasks-panel{display:flex;flex-direction:column;min-height:0;overflow:hidden;scrollbar-gutter:auto;padding-right:clamp(20px,4vw,48px)}
.project-tasks-panel>header{flex:none;margin-bottom:16px}.project-tasks-panel>header p{margin:0}
.project-tasks{display:flex;flex-direction:column;flex:1;min-height:0;gap:12px;overflow:hidden}
.project-tasks>.project-task-toolbar{flex:none;margin:0}.project-tasks>.project-task-diagnostics{flex:none;max-height:100px;overflow:auto;scrollbar-gutter:stable;margin:0}
.project-tasks>.project-capability-layout{position:relative;flex:1;min-height:0;overflow:hidden;align-items:stretch;grid-template-columns:minmax(180px,.8fr) minmax(0,2fr)}
.project-tasks .project-task-roster{display:flex;flex-direction:column;min-height:0;overflow:hidden}
.project-tasks .project-capability-list{display:flex;flex-direction:column;min-height:0;overflow:auto;overscroll-behavior:contain;scrollbar-gutter:stable;padding-right:8px}
.project-tasks .project-task-choice{flex:none}.project-tasks .project-task-pagination{flex:none;margin-top:10px}
.project-tasks .project-task-detail{min-height:0;overflow:auto;overscroll-behavior:contain;scrollbar-gutter:stable;padding-right:calc(20px - var(--dsh-scrollbar-width,8px))}
.project-task-navigation{display:none;flex:none;align-items:center;gap:12px;min-width:0}
.project-task-navigation>span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--dsw-alias-label-secondary)}
.project-task-navigation>button{flex:none}
.project-task-materials{box-sizing:border-box;height:100%;min-height:0;overflow:auto;overscroll-behavior:contain;scrollbar-gutter:stable;padding:24px calc(24px - var(--dsh-scrollbar-width,8px)) 24px 24px;overflow-wrap:anywhere}
.project-task-materials h2{font-size:16px;line-height:24px;margin:0}.project-task-materials h3{font-size:14px;line-height:22px;margin:20px 0 10px}
.project-task-materials header p{margin:6px 0 0}.project-task-materials ul{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:12px}
.project-task-materials li{display:flex;flex-direction:column;align-items:flex-start;min-width:0;gap:4px}.project-task-materials li>button{max-width:100%}
.project-task-materials li>small{padding-left:8px}.project-task-material-file{width:100%;justify-content:flex-start}
.project-task-materials li>button>span:last-child{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.project-task-official-document{height:100%;min-height:0;overflow:hidden}.project-task-official-document [data-textpreview-body]{scrollbar-gutter:stable}
.project-task-commit{box-sizing:border-box;height:100%;min-height:0;overflow:auto;overscroll-behavior:contain;scrollbar-gutter:stable;padding:24px calc(24px - var(--dsh-scrollbar-width,8px)) 24px 24px;overflow-wrap:anywhere}
.project-task-commit h2{font-size:16px;line-height:24px;margin:0}.project-task-commit h3{font-size:14px;line-height:22px;margin:20px 0 10px}.project-task-commit p{margin:8px 0}.project-task-commit-actions{display:flex;align-items:center;flex-wrap:wrap;gap:12px;margin:12px 0}
.project-task-commit-files{display:flex;flex-direction:column;gap:12px;min-width:0}.project-task-commit-file{min-width:0}.project-task-commit .project-task-commit-path{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin-right:8px}
/* The official DiffBlock owns its colors and controls; reserve its horizontal
   scrollbar height so long lines do not move the following content. */
.project-task-commit [data-diff]>div:first-of-type{overflow-x:scroll;scrollbar-gutter:stable}
@container project-tasks (max-width:650px){.project-tasks>.project-capability-layout{grid-template-columns:minmax(0,1fr)}.project-tasks .project-task-detail{display:none}.project-tasks.showing-detail .project-task-detail{display:block}.project-tasks.showing-detail .project-task-roster{display:none}.project-task-navigation{display:flex}}
`;
